name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Notify CI server
      run: "curl -X POST ${{ secrets.CI_URL }} -H 'Content-Type: application/json' -d '{\"name\": \"pvgql\", \"key\": \"${{ secrets.CI_KEY }}\"}'"
